site_name: myValencer
pages:
  - Home: index.md
theme:
  name: null
  custom_dir: material
  language: en
  direction: ltr
  feature:
     tabs: false
  palette:
    primary: turquoise
    accent: turquoise
  font:
     text: Roboto
     code: Roboto Mono
  favicon: assets/images/favicon.png
  logo:
    icon: "\uE80C"
markdown_extensions:
  - admonition
